# ArgoCD Image Updater konfiguratsiooni v채채rtused
image:
  repository: quay.io/argoprojlabs/argocd-image-updater
  tag: v0.12.2
  pullPolicy: Always

config:
  # ArgoCD serveri 체henduse seaded
  argocd.grpc_web: true
  argocd.server_addr: argocd-server.argocd.svc.cluster.local:443
  argocd.insecure: false
  argocd.plaintext: false
  
  # Git repository seaded
  git.commit_user: argocd-image-updater
  git.commit_email: argocd-image-updater@tanelsokolov.dev
  git.commit_message_template: |
    build: automatic update of {{ .AppName }}
    
    {{ range .AppChanges -}}
    updates image {{ .Image }} tag '{{ .OldTag }}' to '{{ .NewTag }}'
    {{ end -}}

# RBAC 천igused
rbac:
  enabled: true

serviceAccount:
  create: true
  name: argocd-image-updater

# Logimise tase
logLevel: info

# Registry seaded
registries:
  - name: Docker Hub
    prefix: docker.io
    api_url: https://registry-1.docker.io
    default: true